### ISSUE TITLE
additional-purchase edit page can't create new item

### ISSUE THREAD

**Issue by chokeslam** [lyrasoft/luna-shopgo#36]
從易讀 yidu [#163](https://github.com/lyrasoft/yidubooks/issues/163) 移過來

看起來是丟了空陣列進去, 需要從套件修復

![yidubooks_–___Sites_yidubooks_vendor_lyrasoft_shopgo_src_Module_Admin_AdditionalPurchase_AdditionalPurchaseEditView_php](https://user-images.githubusercontent.com/34531644/232733664-d678ae4b-fadb-457b-8355-ebaa24bf43a4.png)

**Comment by asika32764** [comment]
Fixed
