### ISSUE TITLE
DiscountRepository getAvailableSelector 中的 query 問題

### ISSUE THREAD

**Issue by chokeslam** [lyrasoft/luna-shopgo#51]
![wushifarm_–___Sites_wushifarm_vendor_lyrasoft_shopgo_src_Repository_DiscountRepository_php](https://github.com/lyrasoft/luna-shopgo/assets/34531644/7c223f00-a83d-4745-b6c0-8545ba15dcfa)

**Comment by ivylai012** [comment]
可能會影響到 https://github.com/lyrasoft/wushifarm/issues/112

**Comment by ivylai012** [comment]
可能會影響到 https://github.com/lyrasoft/wushifarm/issues/113
